apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-client
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 5
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: probe1
        image: 217747396203.dkr.ecr.us-east-1.amazonaws.com/mydockerrepo:client
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: svc-client
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
   - port: 80
     targetPort: 3000
     protocol: TCP
