apiVersion: batch/v1          
kind: Job                     
metadata:
 name: job-test
spec:
 #activeDeadlineSeconds: 60
 backoffLimit: 3
 completions: 4                         
 parallelism: 2
 template:
   metadata:
     name: job-test
   spec:
     containers:
     - name: job
       image: busybox                  
       command: ["echo", "job completed"]   
     restartPolicy: OnFailure 
